[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.7"

[[override]]
  name = "github.com/yieldr/go-auth0"
  source = "https://github.com/harryrose/go-auth0.git"

[prune]
  go-tests = true
  unused-packages = true
